### ISSUE TITLE
Can't find the xp65 environment

### ISSUE THREAD

**Issue by pboubel** [ACCESS-NRI/access-nri-intake-catalog#182] opened 2024-08-08 03:02 UTC
In the 'How do I use it?' section in the docs, currently it says that the hh5 `conda/analysis3-unstable` environment or the xp65 `conda/are` can both be used for the intake catalog on ARE. The issue is that the xp65 environment does not appear in Jupyterlab so I'm assuming it no longer exists.

**Comment by marc-white** [comment] 2024-08-08 03:19
Can confirm I had this same issue about a week ago. It didn't seem to be caused by a failure to load the correct `/gdata` area - it just seems to not exist.

**Comment by dougiesquire** [comment] 2024-08-08 03:21
Ta, my guess is that the xp65 environment has been moved/changed since I wrote the documentation. @rbeucher is that right?

**Comment by rbeucher** [comment] 2024-08-08 03:22
We need to update the doc.

It's 'conda/access-med'

**Comment by dougiesquire** [comment] 2024-08-08 03:24
@pboubel are you interested in testing this and then submitting a PR?

**Comment by pboubel** [comment] 2024-08-08 03:25
Yes, I'm on it :)

**Comment by pboubel** [comment] 2024-08-08 03:47
`conda/access-med` works so I've just submitted a pull request. However, I'll note that the outdated `cosima_cookbook` module is not available in this environment. This means that the 'ACCESS-NRI_Intake_Catalog' tutorial notebook won't fully work as it makes comparisons between the new intake catalog and the old cosima cookbook.

**Comment by dougiesquire** [comment] 2024-08-08 04:01
Closed by #183

**Closed by dougiesquire** 2024-08-08 04:01 UTC
Labels: bug
